---
- hosts: webserver
  become: yes
  tasks: 
  - name: install java on ubuntu
    apt:
      name: "{{ javaonubuntu }}"
      state: present
    when: ansible_os_family == "Debain" 
  - name: install java on amazon
    yum:
      name: "{{ javaonredhat }}"
      state: present
    when: ansible_os_family == "RedHat"     