---
- hosts: webserver
  become: yes
  tasks: 
  - name: add repository
    apt_repository:
      repo: "ppa:webupd8team/java" 
      state: present
      update_cache: yes
  - name: install java7
    apt: 
      name: "{{ javaonubuntu }}" 
      state: present
      update_cache: yes   
    when: ansible_os_family =="Debian"
  - name: install java on amazon
    yum:
      name: "{{ javaonamazon }}"
      state: present
    when: ansible_os_family =="RedHat"     