---
- hosts: webserver
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{ javaonubuntu }}"
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: install java on redhat
    yum:
      name: "{{ javaonredhat }}" 
      state: present
      update_cache: yes
    when: ansible_os_family == "RedHat"   