---
# tasks file for tomrole

- name: install tomcat
  apt:
    name: tomcat7
    state: present


- name: copy tom config into nodes
  template:
    src: templates/tomconfig.j2
    dest: /etc/default/tomcat7
  notify: restarttomcat

- name: install additional packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tomcat7-docs
    - tomcat7-admin
    - tomcat7-examples

- name: copy tom user file into nodes 
  template: 
    src: templates/tomuser.j2
    dest: /etc/tomcat7/tomcat-users.xml
  notify: restarttomcat

